// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type PolicyInitParameters struct {

	// (String) The policy document.
	// The policy document.
	Body *string `json:"body,omitempty" tf:"body,omitempty"`

	// (String) The id of the ISM policy.
	// The id of the ISM policy.
	PolicyID *string `json:"policyId,omitempty" tf:"policy_id,omitempty"`

	// (Number) The primary term of the ISM policy version.
	// The primary term of the ISM policy version.
	PrimaryTerm *float64 `json:"primaryTerm,omitempty" tf:"primary_term,omitempty"`

	// (Number) The sequence number of the ISM policy version.
	// The sequence number of the ISM policy version.
	SeqNo *float64 `json:"seqNo,omitempty" tf:"seq_no,omitempty"`
}

type PolicyObservation struct {

	// (String) The policy document.
	// The policy document.
	Body *string `json:"body,omitempty" tf:"body,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The id of the ISM policy.
	// The id of the ISM policy.
	PolicyID *string `json:"policyId,omitempty" tf:"policy_id,omitempty"`

	// (Number) The primary term of the ISM policy version.
	// The primary term of the ISM policy version.
	PrimaryTerm *float64 `json:"primaryTerm,omitempty" tf:"primary_term,omitempty"`

	// (Number) The sequence number of the ISM policy version.
	// The sequence number of the ISM policy version.
	SeqNo *float64 `json:"seqNo,omitempty" tf:"seq_no,omitempty"`
}

type PolicyParameters struct {

	// (String) The policy document.
	// The policy document.
	// +kubebuilder:validation:Optional
	Body *string `json:"body,omitempty" tf:"body,omitempty"`

	// (String) The id of the ISM policy.
	// The id of the ISM policy.
	// +kubebuilder:validation:Optional
	PolicyID *string `json:"policyId,omitempty" tf:"policy_id,omitempty"`

	// (Number) The primary term of the ISM policy version.
	// The primary term of the ISM policy version.
	// +kubebuilder:validation:Optional
	PrimaryTerm *float64 `json:"primaryTerm,omitempty" tf:"primary_term,omitempty"`

	// (Number) The sequence number of the ISM policy version.
	// The sequence number of the ISM policy version.
	// +kubebuilder:validation:Optional
	SeqNo *float64 `json:"seqNo,omitempty" tf:"seq_no,omitempty"`
}

// PolicySpec defines the desired state of Policy
type PolicySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            PolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PolicyInitParameters `json:"initProvider,omitempty"`
}

// PolicyStatus defines the observed state of Policy.
type PolicyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Policy is the Schema for the Policys API. Provides an OpenSearch Index State Management (ISM) policy. Please refer to the OpenSearch ISM documentation for details.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,opensearch}
type Policy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.body) || (has(self.initProvider) && has(self.initProvider.body))",message="spec.forProvider.body is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.policyId) || (has(self.initProvider) && has(self.initProvider.policyId))",message="spec.forProvider.policyId is a required parameter"
	Spec   PolicySpec   `json:"spec"`
	Status PolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyList contains a list of Policys
type PolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Policy `json:"items"`
}

// Repository type metadata.
var (
	Policy_Kind             = "Policy"
	Policy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Policy_Kind}.String()
	Policy_KindAPIVersion   = Policy_Kind + "." + CRDGroupVersion.String()
	Policy_GroupVersionKind = CRDGroupVersion.WithKind(Policy_Kind)
)

func init() {
	SchemeBuilder.Register(&Policy{}, &PolicyList{})
}
