// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Index) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Monitor) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Role) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Script) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *User) Hub() {}
