//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditInitParameters) DeepCopyInto(out *AuditInitParameters) {
	*out = *in
	if in.DisabledRestCategories != nil {
		in, out := &in.DisabledRestCategories, &out.DisabledRestCategories
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DisabledTransportCategories != nil {
		in, out := &in.DisabledTransportCategories, &out.DisabledTransportCategories
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.EnableRest != nil {
		in, out := &in.EnableRest, &out.EnableRest
		*out = new(bool)
		**out = **in
	}
	if in.EnableTransport != nil {
		in, out := &in.EnableTransport, &out.EnableTransport
		*out = new(bool)
		**out = **in
	}
	if in.ExcludeSensitiveHeaders != nil {
		in, out := &in.ExcludeSensitiveHeaders, &out.ExcludeSensitiveHeaders
		*out = new(bool)
		**out = **in
	}
	if in.IgnoreRequests != nil {
		in, out := &in.IgnoreRequests, &out.IgnoreRequests
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IgnoreUsers != nil {
		in, out := &in.IgnoreUsers, &out.IgnoreUsers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LogRequestBody != nil {
		in, out := &in.LogRequestBody, &out.LogRequestBody
		*out = new(bool)
		**out = **in
	}
	if in.ResolveBulkRequests != nil {
		in, out := &in.ResolveBulkRequests, &out.ResolveBulkRequests
		*out = new(bool)
		**out = **in
	}
	if in.ResolveIndices != nil {
		in, out := &in.ResolveIndices, &out.ResolveIndices
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditInitParameters.
func (in *AuditInitParameters) DeepCopy() *AuditInitParameters {
	if in == nil {
		return nil
	}
	out := new(AuditInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditObservation) DeepCopyInto(out *AuditObservation) {
	*out = *in
	if in.DisabledRestCategories != nil {
		in, out := &in.DisabledRestCategories, &out.DisabledRestCategories
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DisabledTransportCategories != nil {
		in, out := &in.DisabledTransportCategories, &out.DisabledTransportCategories
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.EnableRest != nil {
		in, out := &in.EnableRest, &out.EnableRest
		*out = new(bool)
		**out = **in
	}
	if in.EnableTransport != nil {
		in, out := &in.EnableTransport, &out.EnableTransport
		*out = new(bool)
		**out = **in
	}
	if in.ExcludeSensitiveHeaders != nil {
		in, out := &in.ExcludeSensitiveHeaders, &out.ExcludeSensitiveHeaders
		*out = new(bool)
		**out = **in
	}
	if in.IgnoreRequests != nil {
		in, out := &in.IgnoreRequests, &out.IgnoreRequests
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IgnoreUsers != nil {
		in, out := &in.IgnoreUsers, &out.IgnoreUsers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LogRequestBody != nil {
		in, out := &in.LogRequestBody, &out.LogRequestBody
		*out = new(bool)
		**out = **in
	}
	if in.ResolveBulkRequests != nil {
		in, out := &in.ResolveBulkRequests, &out.ResolveBulkRequests
		*out = new(bool)
		**out = **in
	}
	if in.ResolveIndices != nil {
		in, out := &in.ResolveIndices, &out.ResolveIndices
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditObservation.
func (in *AuditObservation) DeepCopy() *AuditObservation {
	if in == nil {
		return nil
	}
	out := new(AuditObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditParameters) DeepCopyInto(out *AuditParameters) {
	*out = *in
	if in.DisabledRestCategories != nil {
		in, out := &in.DisabledRestCategories, &out.DisabledRestCategories
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DisabledTransportCategories != nil {
		in, out := &in.DisabledTransportCategories, &out.DisabledTransportCategories
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.EnableRest != nil {
		in, out := &in.EnableRest, &out.EnableRest
		*out = new(bool)
		**out = **in
	}
	if in.EnableTransport != nil {
		in, out := &in.EnableTransport, &out.EnableTransport
		*out = new(bool)
		**out = **in
	}
	if in.ExcludeSensitiveHeaders != nil {
		in, out := &in.ExcludeSensitiveHeaders, &out.ExcludeSensitiveHeaders
		*out = new(bool)
		**out = **in
	}
	if in.IgnoreRequests != nil {
		in, out := &in.IgnoreRequests, &out.IgnoreRequests
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IgnoreUsers != nil {
		in, out := &in.IgnoreUsers, &out.IgnoreUsers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LogRequestBody != nil {
		in, out := &in.LogRequestBody, &out.LogRequestBody
		*out = new(bool)
		**out = **in
	}
	if in.ResolveBulkRequests != nil {
		in, out := &in.ResolveBulkRequests, &out.ResolveBulkRequests
		*out = new(bool)
		**out = **in
	}
	if in.ResolveIndices != nil {
		in, out := &in.ResolveIndices, &out.ResolveIndices
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditParameters.
func (in *AuditParameters) DeepCopy() *AuditParameters {
	if in == nil {
		return nil
	}
	out := new(AuditParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceInitParameters) DeepCopyInto(out *ComplianceInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ExternalConfig != nil {
		in, out := &in.ExternalConfig, &out.ExternalConfig
		*out = new(bool)
		**out = **in
	}
	if in.InternalConfig != nil {
		in, out := &in.InternalConfig, &out.InternalConfig
		*out = new(bool)
		**out = **in
	}
	if in.ReadIgnoreUsers != nil {
		in, out := &in.ReadIgnoreUsers, &out.ReadIgnoreUsers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ReadMetadataOnly != nil {
		in, out := &in.ReadMetadataOnly, &out.ReadMetadataOnly
		*out = new(bool)
		**out = **in
	}
	if in.ReadWatchedField != nil {
		in, out := &in.ReadWatchedField, &out.ReadWatchedField
		*out = make([]ReadWatchedFieldInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WriteIgnoreUsers != nil {
		in, out := &in.WriteIgnoreUsers, &out.WriteIgnoreUsers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.WriteLogDiffs != nil {
		in, out := &in.WriteLogDiffs, &out.WriteLogDiffs
		*out = new(bool)
		**out = **in
	}
	if in.WriteMetadataOnly != nil {
		in, out := &in.WriteMetadataOnly, &out.WriteMetadataOnly
		*out = new(bool)
		**out = **in
	}
	if in.WriteWatchedIndices != nil {
		in, out := &in.WriteWatchedIndices, &out.WriteWatchedIndices
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceInitParameters.
func (in *ComplianceInitParameters) DeepCopy() *ComplianceInitParameters {
	if in == nil {
		return nil
	}
	out := new(ComplianceInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceObservation) DeepCopyInto(out *ComplianceObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ExternalConfig != nil {
		in, out := &in.ExternalConfig, &out.ExternalConfig
		*out = new(bool)
		**out = **in
	}
	if in.InternalConfig != nil {
		in, out := &in.InternalConfig, &out.InternalConfig
		*out = new(bool)
		**out = **in
	}
	if in.ReadIgnoreUsers != nil {
		in, out := &in.ReadIgnoreUsers, &out.ReadIgnoreUsers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ReadMetadataOnly != nil {
		in, out := &in.ReadMetadataOnly, &out.ReadMetadataOnly
		*out = new(bool)
		**out = **in
	}
	if in.ReadWatchedField != nil {
		in, out := &in.ReadWatchedField, &out.ReadWatchedField
		*out = make([]ReadWatchedFieldObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WriteIgnoreUsers != nil {
		in, out := &in.WriteIgnoreUsers, &out.WriteIgnoreUsers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.WriteLogDiffs != nil {
		in, out := &in.WriteLogDiffs, &out.WriteLogDiffs
		*out = new(bool)
		**out = **in
	}
	if in.WriteMetadataOnly != nil {
		in, out := &in.WriteMetadataOnly, &out.WriteMetadataOnly
		*out = new(bool)
		**out = **in
	}
	if in.WriteWatchedIndices != nil {
		in, out := &in.WriteWatchedIndices, &out.WriteWatchedIndices
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceObservation.
func (in *ComplianceObservation) DeepCopy() *ComplianceObservation {
	if in == nil {
		return nil
	}
	out := new(ComplianceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceParameters) DeepCopyInto(out *ComplianceParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ExternalConfig != nil {
		in, out := &in.ExternalConfig, &out.ExternalConfig
		*out = new(bool)
		**out = **in
	}
	if in.InternalConfig != nil {
		in, out := &in.InternalConfig, &out.InternalConfig
		*out = new(bool)
		**out = **in
	}
	if in.ReadIgnoreUsers != nil {
		in, out := &in.ReadIgnoreUsers, &out.ReadIgnoreUsers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ReadMetadataOnly != nil {
		in, out := &in.ReadMetadataOnly, &out.ReadMetadataOnly
		*out = new(bool)
		**out = **in
	}
	if in.ReadWatchedField != nil {
		in, out := &in.ReadWatchedField, &out.ReadWatchedField
		*out = make([]ReadWatchedFieldParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WriteIgnoreUsers != nil {
		in, out := &in.WriteIgnoreUsers, &out.WriteIgnoreUsers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.WriteLogDiffs != nil {
		in, out := &in.WriteLogDiffs, &out.WriteLogDiffs
		*out = new(bool)
		**out = **in
	}
	if in.WriteMetadataOnly != nil {
		in, out := &in.WriteMetadataOnly, &out.WriteMetadataOnly
		*out = new(bool)
		**out = **in
	}
	if in.WriteWatchedIndices != nil {
		in, out := &in.WriteWatchedIndices, &out.WriteWatchedIndices
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceParameters.
func (in *ComplianceParameters) DeepCopy() *ComplianceParameters {
	if in == nil {
		return nil
	}
	out := new(ComplianceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Config) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigInitParameters) DeepCopyInto(out *ConfigInitParameters) {
	*out = *in
	if in.Audit != nil {
		in, out := &in.Audit, &out.Audit
		*out = make([]AuditInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Compliance != nil {
		in, out := &in.Compliance, &out.Compliance
		*out = make([]ComplianceInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigInitParameters.
func (in *ConfigInitParameters) DeepCopy() *ConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigList) DeepCopyInto(out *ConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Config, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigList.
func (in *ConfigList) DeepCopy() *ConfigList {
	if in == nil {
		return nil
	}
	out := new(ConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigObservation) DeepCopyInto(out *ConfigObservation) {
	*out = *in
	if in.Audit != nil {
		in, out := &in.Audit, &out.Audit
		*out = make([]AuditObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Compliance != nil {
		in, out := &in.Compliance, &out.Compliance
		*out = make([]ComplianceObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigObservation.
func (in *ConfigObservation) DeepCopy() *ConfigObservation {
	if in == nil {
		return nil
	}
	out := new(ConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigParameters) DeepCopyInto(out *ConfigParameters) {
	*out = *in
	if in.Audit != nil {
		in, out := &in.Audit, &out.Audit
		*out = make([]AuditParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Compliance != nil {
		in, out := &in.Compliance, &out.Compliance
		*out = make([]ComplianceParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigParameters.
func (in *ConfigParameters) DeepCopy() *ConfigParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSpec) DeepCopyInto(out *ConfigSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSpec.
func (in *ConfigSpec) DeepCopy() *ConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigStatus) DeepCopyInto(out *ConfigStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigStatus.
func (in *ConfigStatus) DeepCopy() *ConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadWatchedFieldInitParameters) DeepCopyInto(out *ReadWatchedFieldInitParameters) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Index != nil {
		in, out := &in.Index, &out.Index
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadWatchedFieldInitParameters.
func (in *ReadWatchedFieldInitParameters) DeepCopy() *ReadWatchedFieldInitParameters {
	if in == nil {
		return nil
	}
	out := new(ReadWatchedFieldInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadWatchedFieldObservation) DeepCopyInto(out *ReadWatchedFieldObservation) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Index != nil {
		in, out := &in.Index, &out.Index
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadWatchedFieldObservation.
func (in *ReadWatchedFieldObservation) DeepCopy() *ReadWatchedFieldObservation {
	if in == nil {
		return nil
	}
	out := new(ReadWatchedFieldObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadWatchedFieldParameters) DeepCopyInto(out *ReadWatchedFieldParameters) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Index != nil {
		in, out := &in.Index, &out.Index
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadWatchedFieldParameters.
func (in *ReadWatchedFieldParameters) DeepCopy() *ReadWatchedFieldParameters {
	if in == nil {
		return nil
	}
	out := new(ReadWatchedFieldParameters)
	in.DeepCopyInto(out)
	return out
}
