apiVersion: index.opensearch.upbound.io/v1alpha1
kind: Template
metadata:
  annotations:
    meta.upbound.io/example-id: index/v1alpha1/template
  labels:
    testing.upbound.io/example-name: template_1
  name: template-1
spec:
  forProvider:
    body: |
      {
        "template": "te*",
        "settings": {
          "number_of_shards": 1
        },
        "mappings": {
          "type1": {
            "_source": {
              "enabled": false
            },
            "properties": {
              "host_name": {
                "type": "keyword"
              },
              "created_at": {
                "type": "date",
                "format": "EEE MMM dd HH:mm:ss Z YYYY"
              }
            }
          }
        }
      }
    name: template_1
