// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type DetectionInitParameters struct {

	// (String) The anomaly detection document
	// The anomaly detection document
	Body *string `json:"body,omitempty" tf:"body,omitempty"`
}

type DetectionObservation struct {

	// (String) The anomaly detection document
	// The anomaly detection document
	Body *string `json:"body,omitempty" tf:"body,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type DetectionParameters struct {

	// (String) The anomaly detection document
	// The anomaly detection document
	// +kubebuilder:validation:Optional
	Body *string `json:"body,omitempty" tf:"body,omitempty"`
}

// DetectionSpec defines the desired state of Detection
type DetectionSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DetectionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DetectionInitParameters `json:"initProvider,omitempty"`
}

// DetectionStatus defines the observed state of Detection.
type DetectionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DetectionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Detection is the Schema for the Detections API. Provides an OpenSearch anonaly detection. Please refer to the OpenSearch anomaly detection documentation for details.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,opensearch}
type Detection struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.body) || (has(self.initProvider) && has(self.initProvider.body))",message="spec.forProvider.body is a required parameter"
	Spec   DetectionSpec   `json:"spec"`
	Status DetectionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DetectionList contains a list of Detections
type DetectionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Detection `json:"items"`
}

// Repository type metadata.
var (
	Detection_Kind             = "Detection"
	Detection_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Detection_Kind}.String()
	Detection_KindAPIVersion   = Detection_Kind + "." + CRDGroupVersion.String()
	Detection_GroupVersionKind = CRDGroupVersion.WithKind(Detection_Kind)
)

func init() {
	SchemeBuilder.Register(&Detection{}, &DetectionList{})
}
