apiVersion: opensearch.opensearch.upbound.io/v1alpha1
kind: Index
metadata:
  annotations:
    meta.upbound.io/example-id: opensearch/v1alpha1/index
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    mappings: |
      {
        "people": {
          "_all": {
            "enabled": false
          },
          "properties": {
            "email": {
              "type": "text"
            }
          }
        }
      }
    name: terraform-test
    numberOfReplicas: 1
    numberOfShards: 1
